import {
  IOracleState,
  IRecommendationEngineState,
  exerciseIds,
} from "./interfaces";

const DefaultClickOracle: IOracleState = {
  contextFeatures: ["happy", "sad"],
  exerciseFeatures: [
    "three_five_mins",
    "five_seven_mins",
    "seven_ten_mins",
    "defuse",
    "zoom_out",
    // 'feeling_stressed',
    // 'feeling_angry',
    "mood_boost",
    "self_compassion",
    "relax",
    "energize",
    // 'feeling_anxious',
    "grounding",
    // 'feeling_blue',
    "focus",
    "shift_perspective",
    "introspect",
    "breathing",
    "article",
    "ACT",
    "Mindfulness",
    "Relaxation",
    "PositivePsychology",
  ],
  exerciseIds: exerciseIds,
  learningRate: 0.01,
  contextExerciseInteractions: true,
  contextExerciseFeatureInteractions: true,
  useInversePropensityWeighting: true,
  negativeClassWeight: 0.5,
  targetLabel: "clicked",
  weights: {
    intercept: -0.7,
    shape_your_thoughts: 0,
    self_compassion_break: 0,
    body_scan: 0,
    progressive_muscle_relaxation: 0,
    compassionate_friend: 0,
    naming_thanking_mind: 0,
    "3_good_things": 0,
    labeling: 0,
    leaves_on_stream: 0,
    bad_news_radio: 0,
    milk_milk_milk: 0,
    five_senses: 0,
    tracking_thought_in_time: 0,
    alternate_nostril_breathing: 0,
    boxed_breathing: 0,
    diaphragmatic_breathing: 0,
    talking_to_friend: 0,
    savouring: 0,
    positive_self_talk: 0,
    follow_your_breath: 0,
    three_five_mins: 0,
    five_seven_mins: 0,
    seven_ten_mins: 0,
    defuse: 0,
    zoom_out: 0,
    mood_boost: 0,
    self_compassion: 0,
    relax: 0,
    energize: 0,
    grounding: 0,
    focus: 0,
    shift_perspective: 0,
    introspect: 0,
    breathing: 0,
    article: 0,
    ACT: 0,
    Mindfulness: 0,
    Relaxation: 0,
    PositivePsychology: 0,
    "happy*shape_your_thoughts": 0,
    "happy*self_compassion_break": 0,
    "happy*body_scan": 0,
    "happy*progressive_muscle_relaxation": 0,
    "happy*compassionate_friend": 0,
    "happy*naming_thanking_mind": 0,
    "happy*3_good_things": 0,
    "happy*labeling": 0,
    "happy*leaves_on_stream": 0,
    "happy*bad_news_radio": 0,
    "happy*milk_milk_milk": 0,
    "happy*five_senses": 0,
    "happy*tracking_thought_in_time": 0,
    "happy*alternate_nostril_breathing": 0,
    "happy*boxed_breathing": 0,
    "happy*diaphragmatic_breathing": 0,
    "happy*talking_to_friend": 0,
    "happy*savouring": 0,
    "happy*positive_self_talk": 0,
    "happy*follow_your_breath": 0,
    "sad*shape_your_thoughts": 0,
    "sad*self_compassion_break": 0,
    "sad*body_scan": 0,
    "sad*progressive_muscle_relaxation": 0,
    "sad*compassionate_friend": 0,
    "sad*naming_thanking_mind": 0,
    "sad*3_good_things": 0,
    "sad*labeling": 0,
    "sad*leaves_on_stream": 0,
    "sad*bad_news_radio": 0,
    "sad*milk_milk_milk": 0,
    "sad*five_senses": 0,
    "sad*tracking_thought_in_time": 0,
    "sad*alternate_nostril_breathing": 0,
    "sad*boxed_breathing": 0,
    "sad*diaphragmatic_breathing": 0,
    "sad*talking_to_friend": 0,
    "sad*savouring": 0,
    "sad*positive_self_talk": 0,
    "sad*follow_your_breath": 0,
    "happy*three_five_mins": 0,
    "happy*five_seven_mins": 0,
    "happy*seven_ten_mins": 0,
    "happy*defuse": 0,
    "happy*zoom_out": 0,
    "happy*mood_boost": 0,
    "happy*self_compassion": 0,
    "happy*relax": 0,
    "happy*energize": 0,
    "happy*grounding": 0,
    "happy*focus": 0,
    "happy*shift_perspective": 0,
    "happy*introspect": 0,
    "happy*breathing": 0,
    "happy*article": 0,
    "happy*ACT": 0,
    "happy*Mindfulness": 0,
    "happy*Relaxation": 0,
    "happy*PositivePsychology": 1,
    "sad*three_five_mins": 0,
    "sad*five_seven_mins": 0,
    "sad*seven_ten_mins": 0,
    "sad*defuse": 0,
    "sad*zoom_out": 0,
    "sad*mood_boost": 0,
    "sad*self_compassion": 0,
    "sad*relax": 0,
    "sad*energize": 0,
    "sad*grounding": 0,
    "sad*focus": 0,
    "sad*shift_perspective": 0,
    "sad*introspect": 0,
    "sad*breathing": 0,
    "sad*article": 0,
    "sad*ACT": 0,
    "sad*Mindfulness": 0,
    "sad*Relaxation": 0,
    "sad*PositivePsychology": 0,
  },
};

const DefaultLikingOracle: IOracleState = {
  contextFeatures: ["happy", "sad"],
  exerciseFeatures: [
    // "three_five_mins",
    // "five_seven_mins",
    // "seven_ten_mins",
    // "defuse",
    // "zoom_out",
    // 'feeling_stressed',
    // 'feeling_angry',
    // "mood_boost",
    // "self_compassion",
    // "relax",
    // "energize",
    // 'feeling_anxious',
    // "grounding",
    // 'feeling_blue',
    // "focus",
    // "shift_perspective",
    // "introspect",
    // "breathing",
    // "article",
    "ACT",
    "Mindfulness",
    "Relaxation",
    "PositivePsychology",
  ],
  exerciseIds: exerciseIds,
  learningRate: 2.0,
  contextExerciseInteractions: true,
  contextExerciseFeatureInteractions: false,
  useInversePropensityWeighting: false,
  negativeClassWeight: 1.0,
  targetLabel: "liking",
  weights: {
    intercept: 0,
    shape_your_thoughts: 0,
    self_compassion_break: 0,
    body_scan: 0,
    progressive_muscle_relaxation: 0,
    compassionate_friend: 0,
    naming_thanking_mind: 0,
    "3_good_things": 0,
    labeling: 0,
    leaves_on_stream: 0,
    bad_news_radio: 0,
    milk_milk_milk: 0,
    five_senses: 0,
    tracking_thought_in_time: 0,
    alternate_nostril_breathing: 0,
    boxed_breathing: 0,
    diaphragmatic_breathing: 0,
    talking_to_friend: 0,
    savouring: 0,
    positive_self_talk: 0,
    follow_your_breath: 0,
    ACT: 0,
    Mindfulness: 0,
    Relaxation: 0,
    PositivePsychology: 0,
    three_five_mins: 0,
    five_seven_mins: 0,
    grounding: 0,
    feeling_blue: 0,
    focus: 0,
    shift_perspective: 0,
    defuse: 0,
    seven_ten_mins: 0,
    introspect: 0,
    breathing: 0,
    zoom_out: 0,
    article: 0,
    feeling_stressed: 0,
    feeling_angry: 0,
    mood_boost: 0,
    self_compassion: 0,
    relax: 0,
    energize: 0,
    feeling_anxious: 0,
    "happy*shape_your_thoughts": 0,
    "happy*self_compassion_break": 0,
    "happy*body_scan": 0,
    "happy*progressive_muscle_relaxation": 0,
    "happy*compassionate_friend": 0,
    "happy*naming_thanking_mind": 0,
    "happy*3_good_things": 0,
    "happy*labeling": 0,
    "happy*leaves_on_stream": 0,
    "happy*bad_news_radio": 0,
    "happy*milk_milk_milk": 0,
    "happy*five_senses": 0,
    "happy*tracking_thought_in_time": 0,
    "happy*alternate_nostril_breathing": 0,
    "happy*boxed_breathing": 0,
    "happy*diaphragmatic_breathing": 0,
    "happy*talking_to_friend": 0,
    "happy*savouring": 0,
    "happy*positive_self_talk": 0,
    "happy*follow_your_breath": 0,
    "sad*shape_your_thoughts": 0,
    "sad*self_compassion_break": 0,
    "sad*body_scan": 0,
    "sad*progressive_muscle_relaxation": 0,
    "sad*compassionate_friend": 0,
    "sad*naming_thanking_mind": 0,
    "sad*3_good_things": 0,
    "sad*labeling": 0,
    "sad*leaves_on_stream": 0,
    "sad*bad_news_radio": 0,
    "sad*milk_milk_milk": 0,
    "sad*five_senses": 0,
    "sad*tracking_thought_in_time": 0,
    "sad*alternate_nostril_breathing": 0,
    "sad*boxed_breathing": 0,
    "sad*diaphragmatic_breathing": 0,
    "sad*talking_to_friend": 0,
    "sad*savouring": 0,
    "sad*positive_self_talk": 0,
    "sad*follow_your_breath": 0,
    "happy*ACT": 0,
    "happy*Mindfulness": 0,
    "happy*Relaxation": 0,
    "happy*PositivePsychology": 0,
    "happy*three_five_mins": 0,
    "happy*five_seven_mins": 0,
    "happy*grounding": 0,
    "happy*feeling_blue": 0,
    "happy*focus": 0,
    "happy*shift_perspective": 0,
    "happy*defuse": 0,
    "happy*seven_ten_mins": 0,
    "happy*introspect": 0,
    "happy*breathing": 0,
    "happy*zoom_out": 0,
    "happy*article": 0,
    "happy*feeling_stressed": 0,
    "happy*feeling_angry": 0,
    "happy*mood_boost": 0,
    "happy*self_compassion": 0,
    "happy*relax": 0,
    "happy*energize": 0,
    "happy*feeling_anxious": 0,
    "sad*ACT": 0,
    "sad*Mindfulness": 0,
    "sad*Relaxation": 0,
    "sad*PositivePsychology": 0,
    "sad*three_five_mins": 0,
    "sad*five_seven_mins": 0,
    "sad*grounding": 0,
    "sad*feeling_blue": 0,
    "sad*focus": 0,
    "sad*shift_perspective": 0,
    "sad*defuse": 0,
    "sad*seven_ten_mins": 0,
    "sad*introspect": 0,
    "sad*breathing": 0,
    "sad*zoom_out": 0,
    "sad*article": 0,
    "sad*feeling_stressed": 0,
    "sad*feeling_angry": 0,
    "sad*mood_boost": 0,
    "sad*self_compassion": 0,
    "sad*relax": 0,
    "sad*energize": 0,
    "sad*feeling_anxious": 0,
  },
};

const DefaultRecommendationEngine: IRecommendationEngineState = {
  clickOracleState: DefaultClickOracle,
  likingOracleState: DefaultLikingOracle,
  softmaxBeta: 5.0,
  likingWeight: 0.2,
  nRecommendations: 3,
};

export { DefaultClickOracle, DefaultLikingOracle, DefaultRecommendationEngine };
