import {
  IOracleState,
  IRecommendationEngineState,
  exerciseIds,
} from "./interfaces";

const DefaultClickOracle: IOracleState = {
  contextFeatures: ["happy", "sad"],
  exerciseFeatures: [
    "three_five_mins",
    "five_seven_mins",
    "seven_ten_mins",
    "defuse",
    "zoom_out",
    // 'feeling_stressed',
    // 'feeling_angry',
    "mood_boost",
    "self_compassion",
    "relax",
    "energize",
    // 'feeling_anxious',
    "grounding",
    // 'feeling_blue',
    "focus",
    "shift_perspective",
    "introspect",
    "breathing",
    "article",
    "ACT",
    "Mindfulness",
    "Relaxation",
    "PositivePsychology",
  ],
  exerciseIds: exerciseIds,
  learningRate: 0.01,
  contextExerciseInteractions: true,
  contextExerciseFeatureInteractions: true,
  useInversePropensityWeighting: true,
  negativeClassWeight: 0.5,
  targetLabel: "clicked",
  weights: {intercept: -0.7},
};

const DefaultLikingOracle: IOracleState = {
  contextFeatures: ["happy", "sad"],
  exerciseFeatures: [
    // "three_five_mins",
    // "five_seven_mins",
    // "seven_ten_mins",
    // "defuse",
    // "zoom_out",
    // 'feeling_stressed',
    // 'feeling_angry',
    // "mood_boost",
    // "self_compassion",
    // "relax",
    // "energize",
    // 'feeling_anxious',
    // "grounding",
    // 'feeling_blue',
    // "focus",
    // "shift_perspective",
    // "introspect",
    // "breathing",
    // "article",
    "ACT",
    "Mindfulness",
    "Relaxation",
    "PositivePsychology",
  ],
  exerciseIds: exerciseIds,
  learningRate: 2.0,
  contextExerciseInteractions: true,
  contextExerciseFeatureInteractions: false,
  useInversePropensityWeighting: false,
  negativeClassWeight: 1.0,
  targetLabel: "liking",
  weights: {},
};

const DefaultHelpfulnessOracle: IOracleState = {
    contextFeatures: ["happy", "sad"],
    exerciseFeatures: [
      // "three_five_mins",
      // "five_seven_mins",
      // "seven_ten_mins",
      // "defuse",
      // "zoom_out",
      // 'feeling_stressed',
      // 'feeling_angry',
      // "mood_boost",
      // "self_compassion",
      // "relax",
      // "energize",
      // 'feeling_anxious',
      // "grounding",
      // 'feeling_blue',
      // "focus",
      // "shift_perspective",
      // "introspect",
      // "breathing",
      // "article",
      "ACT",
      "Mindfulness",
      "Relaxation",
      "PositivePsychology",
    ],
    exerciseIds: exerciseIds,
    learningRate: 2.0,
    contextExerciseInteractions: true,
    contextExerciseFeatureInteractions: false,
    useInversePropensityWeighting: false,
    negativeClassWeight: 1.0,
    targetLabel: "helpfulness",
    weights: {},
  };

const DefaultRecommendationEngine: IRecommendationEngineState = {
  clickOracleState: DefaultClickOracle,
  likingOracleState: DefaultLikingOracle,
  helpfulnessOracleState: DefaultHelpfulnessOracle,
  softmaxBeta: 5.0,
  clickWeight: 0.7,
  likingWeight: 0.15,
  helpfulnessWeight: 0.15,
  nRecommendations: 3,
};

export { DefaultClickOracle, DefaultLikingOracle, DefaultHelpfulnessOracle, DefaultRecommendationEngine };
