import { IExercise } from "./IExercise";
import { YesNo } from "./YesNo";

export const Exercises: IExercise[] = [
    // {
    //     ExerciseId: 'articles_act',
    //     ExerciseName: 'Article ACT',
    //     Features: {
    //         three_five_mins: YesNo.No,
    //         five_seven_mins: YesNo.Yes,
    //         seven_ten_mins: YesNo.No,
    //         defuse: YesNo.No,
    //         zoom_out: YesNo.No,
    //         feeling_stressed: YesNo.No,
    //         feeling_angry: YesNo.No,
    //         mood_boost: YesNo.No,
    //         self_compassion: YesNo.No,
    //         relax: YesNo.No,
    //         energize: YesNo.No,
    //         feeling_anxious: YesNo.No,
    //         grounding: YesNo.No,
    //         feeling_blue: YesNo.No,
    //         focus: YesNo.No,
    //         shift_perspective: YesNo.No,
    //         introspect: YesNo.No,
    //         breathing: YesNo.No,
    //         article: YesNo.Yes,
    //         ACT: YesNo.Yes,
    //         Mindfulness: YesNo.No,
    //         Relaxation: YesNo.No,
    //         PositivePsychology: YesNo.No,
    //     },
    // },
    {
        ExerciseId: 'shape_your_thoughts',
        ExerciseName: 'Shape Your Thoughts',
        Features: {
            three_five_mins: YesNo.No,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.Yes,
            defuse: YesNo.Yes,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
            ACT: YesNo.Yes,
            Mindfulness: YesNo.No,
            Relaxation: YesNo.No,
            PositivePsychology: YesNo.No,
        },
    },
    {
        ExerciseId: 'self_compassion_break',
        ExerciseName: 'Self Compassion Break',
        Features: {
            'three_five_mins': YesNo.Yes,
            'five_seven_mins': YesNo.No,
            'seven_ten_mins': YesNo.No,
            'defuse': YesNo.No,
            'zoom_out': YesNo.No,
            'feeling_stressed': YesNo.No,
            'feeling_angry': YesNo.No,
            'mood_boost': YesNo.No,
            'self_compassion': YesNo.Yes,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
            ACT: YesNo.No,
            Mindfulness: YesNo.No,
            Relaxation: YesNo.No,
            PositivePsychology: YesNo.Yes,
        },
    },
    {
        ExerciseId: 'body_scan',
        ExerciseName: 'Body Scan',
        Features: {
            'three_five_mins': YesNo.No,
            'five_seven_mins': YesNo.No,
            'seven_ten_mins': YesNo.Yes,
            'defuse': YesNo.No,
            'zoom_out': YesNo.No,
            'feeling_stressed': YesNo.No,
            'feeling_angry': YesNo.No,
            'mood_boost': YesNo.No,
            'self_compassion': YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.Yes,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
            ACT: YesNo.No,
            Mindfulness: YesNo.Yes,
            Relaxation: YesNo.No,
            PositivePsychology: YesNo.No,
        },
    },
    // {
    //     ExerciseId: 'article_mindfulness',
    //     ExerciseName: 'Article Mindfulness',
    //     Features: {
    //         'three_five_mins': YesNo.Yes,
    //         'five_seven_mins': YesNo.No,
    //         'seven_ten_mins': YesNo.No,
    //         'defuse': YesNo.No,
    //         'zoom_out': YesNo.No,
    //         'feeling_stressed': YesNo.No,
    //         'feeling_angry': YesNo.No,
    //         'mood_boost': YesNo.No,
    //         'self_compassion': YesNo.No,
    //         relax: YesNo.No,
    //         energize: YesNo.No,
    //         feeling_anxious: YesNo.No,
    //         grounding: YesNo.Yes,
    //         feeling_blue: YesNo.No,
    //         focus: YesNo.No,
    //         shift_perspective: YesNo.No,
    //         introspect: YesNo.No,
    //         breathing: YesNo.No,
    //         article: YesNo.Yes,
    //         ACT: YesNo.No,
    //         Mindfulness: YesNo.Yes,
    //         Relaxation: YesNo.No,
    //         PositivePsychology: YesNo.No,
    //     },
    // },
    {
        ExerciseId: 'progressive_muscle_relaxation',
        ExerciseName: 'Progressive Muscle Relaxation',
        Features: {
            'three_five_mins': YesNo.No,
            'five_seven_mins': YesNo.No,
            'seven_ten_mins': YesNo.Yes,
            'defuse': YesNo.No,
            'zoom_out': YesNo.No,
            'feeling_stressed': YesNo.Yes,
            'feeling_angry': YesNo.No,
            'mood_boost': YesNo.No,
            'self_compassion': YesNo.No,
            relax: YesNo.Yes,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.Yes,
            feeling_blue: YesNo.No,
            focus: YesNo.Yes,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
            ACT: YesNo.No,
            Mindfulness: YesNo.No,
            Relaxation: YesNo.Yes,
            PositivePsychology: YesNo.No,
        },
    },
    // {
    //     ExerciseId: 'article_breathing_relaxation',
    //     ExerciseName: 'Article Breathing Relaxation',
    //     Features: {
    //         'three_five_mins': YesNo.Yes,
    //         'five_seven_mins': YesNo.No,
    //         'seven_ten_mins': YesNo.No,
    //         'defuse': YesNo.No,
    //         'zoom_out': YesNo.No,
    //         'feeling_stressed': YesNo.Yes,
    //         'feeling_angry': YesNo.Yes,
    //         'mood_boost': YesNo.Yes,
    //         'self_compassion': YesNo.No,
    //         relax: YesNo.Yes,
    //         energize: YesNo.Yes,
    //         feeling_anxious: YesNo.Yes,
    //         grounding: YesNo.No,
    //         feeling_blue: YesNo.Yes,
    //         focus: YesNo.No,
    //         shift_perspective: YesNo.No,
    //         introspect: YesNo.No,
    //         breathing: YesNo.Yes,
    //         article: YesNo.Yes,
    //     },
    // },
    {
        ExerciseId: 'compassionate_friend',
        ExerciseName: 'Compassionate Friend',
        Features: {
            'three_five_mins': YesNo.No,
            'five_seven_mins': YesNo.No,
            'seven_ten_mins': YesNo.Yes,
            'defuse': YesNo.No,
            'zoom_out': YesNo.No,
            'feeling_stressed': YesNo.No,
            'feeling_angry': YesNo.No,
            'mood_boost': YesNo.No,
            'self_compassion': YesNo.Yes,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
            ACT: YesNo.No,
            Mindfulness: YesNo.No,
            Relaxation: YesNo.No,
            PositivePsychology: YesNo.No,
        },
    },
    {
        ExerciseId: 'naming_thanking_mind',
        ExerciseName: 'Naming&Thanking mind',
        Features: {
            three_five_mins: YesNo.Yes,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.Yes,
            zoom_out: YesNo.Yes,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
            ACT: YesNo.Yes,
            Mindfulness: YesNo.No,
            Relaxation: YesNo.No,
            PositivePsychology: YesNo.No,
        },
    },
    {
        ExerciseId: '3_good_things',
        ExerciseName: '3 Good Things',
        Features: {
            three_five_mins: YesNo.Yes,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.No,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.Yes,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
            ACT: YesNo.No,
            Mindfulness: YesNo.No,
            Relaxation: YesNo.No,
            PositivePsychology: YesNo.Yes,
        },
    },
    {
        ExerciseId: 'labeling',
        ExerciseName: 'Labeling',
        Features: {
            three_five_mins: YesNo.Yes,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.Yes,
            zoom_out: YesNo.Yes,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
            ACT: YesNo.Yes,
            Mindfulness: YesNo.No,
            Relaxation: YesNo.No,
            PositivePsychology: YesNo.No,
        },
    },
    // {
    //     ExerciseId: 'article_self_compassion',
    //     ExerciseName: 'Article self compassion',
    //     Features: {
    //         three_five_mins: YesNo.Yes,
    //         five_seven_mins: YesNo.No,
    //         seven_ten_mins: YesNo.No,
    //         defuse: YesNo.No,
    //         zoom_out: YesNo.No,
    //         feeling_stressed: YesNo.No,
    //         feeling_angry: YesNo.No,
    //         mood_boost: YesNo.No,
    //         self_compassion: YesNo.Yes,
    //         relax: YesNo.No,
    //         energize: YesNo.No,
    //         feeling_anxious: YesNo.No,
    //         grounding: YesNo.No,
    //         feeling_blue: YesNo.No,
    //         focus: YesNo.No,
    //         shift_perspective: YesNo.No,
    //         introspect: YesNo.No,
    //         breathing: YesNo.No,
    //         article: YesNo.Yes,
    //         ACT: YesNo.No,
    //         Mindfulness: YesNo.No,
    //         Relaxation: YesNo.No,
    //         PositivePsychology: YesNo.No,
    //     },
    // },
    {
        ExerciseId: 'leaves_on_stream',
        ExerciseName: 'Leaves on a stream',
        Features: {
            three_five_mins: YesNo.No,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.Yes,
            defuse: YesNo.Yes,
            zoom_out: YesNo.Yes,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
            ACT: YesNo.Yes,
            Mindfulness: YesNo.No,
            Relaxation: YesNo.No,
            PositivePsychology: YesNo.No,
        },
    },
    {
        ExerciseId: 'bad_news_radio',
        ExerciseName: 'Bad News Radio',
        Features: {
            three_five_mins: YesNo.Yes,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.Yes,
            zoom_out: YesNo.Yes,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
            ACT: YesNo.Yes,
            Mindfulness: YesNo.No,
            Relaxation: YesNo.No,
            PositivePsychology: YesNo.No,
        },
    },
    {
        ExerciseId: 'milk_milk_milk',
        ExerciseName: 'Milk Milk Milk',
        Features: {
            three_five_mins: YesNo.Yes,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.Yes,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
            ACT: YesNo.Yes,
            Mindfulness: YesNo.No,
            Relaxation: YesNo.No,
            PositivePsychology: YesNo.No,
        },
    },
    // {
    //     ExerciseId: 'article_breathing_relaxation',
    //     ExerciseName: 'Article Breathing relaxation',
    //     Features: {
    //         three_five_mins: YesNo.Yes,
    //         five_seven_mins: YesNo.No,
    //         seven_ten_mins: YesNo.No,
    //         defuse: YesNo.No,
    //         zoom_out: YesNo.No,
    //         feeling_stressed: YesNo.No,
    //         feeling_angry: YesNo.No,
    //         mood_boost: YesNo.Yes,
    //         self_compassion: YesNo.No,
    //         relax: YesNo.No,
    //         energize: YesNo.Yes,
    //         feeling_anxious: YesNo.Yes,
    //         grounding: YesNo.No,
    //         feeling_blue: YesNo.Yes,
    //         focus: YesNo.No,
    //         shift_perspective: YesNo.No,
    //         introspect: YesNo.No,
    //         breathing: YesNo.Yes,
    //         article: YesNo.Yes,
    //         ACT: YesNo.No,
    //         Mindfulness: YesNo.No,
    //         Relaxation: YesNo.Yes,
    //         PositivePsychology: YesNo.No,
    //     },
    // },
    {
        ExerciseId: 'five_senses',
        ExerciseName: 'Five Senses',
        Features: {
            three_five_mins: YesNo.No,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.Yes,
            defuse: YesNo.No,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.Yes,
            feeling_angry: YesNo.Yes,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.Yes,
            feeling_blue: YesNo.Yes,
            focus: YesNo.Yes,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
            ACT: YesNo.No,
            Mindfulness: YesNo.Yes,
            Relaxation: YesNo.No,
            PositivePsychology: YesNo.No,
        },
    },
    {
        ExerciseId: 'tracking_thought_in_time',
        ExerciseName: 'Tracking thoughts in time',
        Features: {
            three_five_mins: YesNo.Yes,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.No,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.Yes,
            feeling_blue: YesNo.No,
            focus: YesNo.Yes,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
            ACT: YesNo.No,
            Mindfulness: YesNo.Yes,
            Relaxation: YesNo.No,
            PositivePsychology: YesNo.No,
        },
    },
    {
        ExerciseId: 'alternate_nostril_breathing',
        ExerciseName: 'Alternate nostril breathing',
        Features: {
            three_five_mins: YesNo.No,
            five_seven_mins: YesNo.Yes,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.No,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.Yes,
            feeling_angry: YesNo.Yes,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.Yes,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.Yes,
            article: YesNo.No,
            ACT: YesNo.No,
            Mindfulness: YesNo.No,
            Relaxation: YesNo.Yes,
            PositivePsychology: YesNo.No,
        },
    },
    {
        ExerciseId: 'boxed_breathing',
        ExerciseName: 'Boxed Breathing',
        Features: {
            three_five_mins: YesNo.Yes,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.No,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.Yes,
            feeling_angry: YesNo.Yes,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.Yes,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.Yes,
            article: YesNo.No,
            ACT: YesNo.No,
            Mindfulness: YesNo.No,
            Relaxation: YesNo.Yes,
            PositivePsychology: YesNo.No,
        },
    },
    {
        ExerciseId: 'diaphragmatic_breathing',
        ExerciseName: 'Diaphragmatic Breathing',
        Features: {
            three_five_mins: YesNo.No,
            five_seven_mins: YesNo.Yes,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.No,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.Yes,
            feeling_angry: YesNo.Yes,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.Yes,
            article: YesNo.No,
            ACT: YesNo.No,
            Mindfulness: YesNo.No,
            Relaxation: YesNo.Yes,
            PositivePsychology: YesNo.No,
        },
    },
    {
        ExerciseId: 'talking_to_friend',
        ExerciseName: 'Talking to a friend',
        Features: {
            three_five_mins: YesNo.No,
            five_seven_mins: YesNo.Yes,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.No,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.No,
            self_compassion: YesNo.Yes,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
            ACT: YesNo.No,
            Mindfulness: YesNo.No,
            Relaxation: YesNo.No,
            PositivePsychology: YesNo.No,
        },
    },
    // {
    //     ExerciseId: 'article_positive_psychology',
    //     ExerciseName: 'Article Positive Psychology',
    //     Features: {
    //         three_five_mins: YesNo.No,
    //         five_seven_mins: YesNo.Yes,
    //         seven_ten_mins: YesNo.No,
    //         defuse: YesNo.No,
    //         zoom_out: YesNo.No,
    //         feeling_stressed: YesNo.No,
    //         feeling_angry: YesNo.No,
    //         mood_boost: YesNo.Yes,
    //         self_compassion: YesNo.No,
    //         relax: YesNo.No,
    //         energize: YesNo.Yes,
    //         feeling_anxious: YesNo.No,
    //         grounding: YesNo.Yes,
    //         feeling_blue: YesNo.No,
    //         focus: YesNo.No,
    //         shift_perspective: YesNo.No,
    //         introspect: YesNo.No,
    //         breathing: YesNo.No,
    //         article: YesNo.Yes,
    //         ACT: YesNo.No,
    //         Mindfulness: YesNo.No,
    //         Relaxation: YesNo.No,
    //         PositivePsychology: YesNo.Yes,
    //     },
    // },
    {
        ExerciseId: 'savouring',
        ExerciseName: 'Savouring',
        Features: {
            three_five_mins: YesNo.No,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.Yes,
            defuse: YesNo.No,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.Yes,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
            ACT: YesNo.No,
            Mindfulness: YesNo.No,
            Relaxation: YesNo.No,
            PositivePsychology: YesNo.Yes,
        },
    },
    {
        ExerciseId: 'positive_self_talk',
        ExerciseName: 'Positive Self Talk',
        Features: {
            three_five_mins: YesNo.No,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.Yes,
            defuse: YesNo.No,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.Yes,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
            ACT: YesNo.No,
            Mindfulness: YesNo.No,
            Relaxation: YesNo.No,
            PositivePsychology: YesNo.Yes,
        },
    },
    {
        ExerciseId: 'follow_your_breath',
        ExerciseName: 'Follow Your Breath',
        Features: {
            three_five_mins: YesNo.No,
            five_seven_mins: YesNo.Yes,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.No,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.Yes,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.Yes,
            article: YesNo.No,
            ACT: YesNo.No,
            Mindfulness: YesNo.Yes,
            Relaxation: YesNo.No,
            PositivePsychology: YesNo.No,
        },
    },
    
]

// exerciseIds is a list of all the exercise ExerciseNames:
export const exerciseIds = Exercises.map((exercise) => exercise.ExerciseId);