import { IExcercise } from "./IExcercise";
import { YesNo } from "./YesNo";

export const Exercises: IExcercise[] = [
    {
        InternalName: 'articles_act',
        DisplayName: 'Article ACT',
        Features: {
            three_five_mins: YesNo.No,
            five_seven_mins: YesNo.Yes,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.No,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.Yes,
        },
    },
    {
        InternalName: 'shape_your_thoughts',
        DisplayName: 'Shape Your Thoughts',
        Features: {
            three_five_mins: YesNo.No,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.Yes,
            defuse: YesNo.Yes,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
        },
    },
    {
        InternalName: 'self_compassion_break',
        DisplayName: 'Self Compassion Break',
        Features: {
            'three_five_mins': YesNo.Yes,
            'five_seven_mins': YesNo.No,
            'seven_ten_mins': YesNo.No,
            'defuse': YesNo.No,
            'zoom_out': YesNo.No,
            'feeling_stressed': YesNo.No,
            'feeling_angry': YesNo.No,
            'mood_boost': YesNo.No,
            'self_compassion': YesNo.Yes,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
        },
    },
    {
        InternalName: 'body_scan',
        DisplayName: 'Body Scan',
        Features: {
            'three_five_mins': YesNo.No,
            'five_seven_mins': YesNo.No,
            'seven_ten_mins': YesNo.Yes,
            'defuse': YesNo.No,
            'zoom_out': YesNo.No,
            'feeling_stressed': YesNo.No,
            'feeling_angry': YesNo.No,
            'mood_boost': YesNo.No,
            'self_compassion': YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.Yes,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
        },
    },
    {
        InternalName: 'article_mindfulness',
        DisplayName: 'Article Mindfulness',
        Features: {
            'three_five_mins': YesNo.Yes,
            'five_seven_mins': YesNo.No,
            'seven_ten_mins': YesNo.No,
            'defuse': YesNo.No,
            'zoom_out': YesNo.No,
            'feeling_stressed': YesNo.No,
            'feeling_angry': YesNo.No,
            'mood_boost': YesNo.No,
            'self_compassion': YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.Yes,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.Yes,
        },
    },
    {
        InternalName: 'progressive_muscle_relaxation',
        DisplayName: 'Progressive Muscle Relaxation',
        Features: {
            'three_five_mins': YesNo.No,
            'five_seven_mins': YesNo.No,
            'seven_ten_mins': YesNo.Yes,
            'defuse': YesNo.No,
            'zoom_out': YesNo.No,
            'feeling_stressed': YesNo.Yes,
            'feeling_angry': YesNo.No,
            'mood_boost': YesNo.No,
            'self_compassion': YesNo.No,
            relax: YesNo.Yes,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.Yes,
            feeling_blue: YesNo.No,
            focus: YesNo.Yes,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
        },
    },
    // {
    //     InternalName: 'article_breathing_relaxation',
    //     DisplayName: 'Article Breathing Relaxation',
    //     Features: {
    //         'three_five_mins': YesNo.Yes,
    //         'five_seven_mins': YesNo.No,
    //         'seven_ten_mins': YesNo.No,
    //         'defuse': YesNo.No,
    //         'zoom_out': YesNo.No,
    //         'feeling_stressed': YesNo.Yes,
    //         'feeling_angry': YesNo.Yes,
    //         'mood_boost': YesNo.Yes,
    //         'self_compassion': YesNo.No,
    //         relax: YesNo.Yes,
    //         energize: YesNo.Yes,
    //         feeling_anxious: YesNo.Yes,
    //         grounding: YesNo.No,
    //         feeling_blue: YesNo.Yes,
    //         focus: YesNo.No,
    //         shift_perspective: YesNo.No,
    //         introspect: YesNo.No,
    //         breathing: YesNo.Yes,
    //         article: YesNo.Yes,
    //     },
    // },
    {
        InternalName: 'compassionate_friend',
        DisplayName: 'Compassionate Friend',
        Features: {
            'three_five_mins': YesNo.No,
            'five_seven_mins': YesNo.No,
            'seven_ten_mins': YesNo.Yes,
            'defuse': YesNo.No,
            'zoom_out': YesNo.No,
            'feeling_stressed': YesNo.No,
            'feeling_angry': YesNo.No,
            'mood_boost': YesNo.No,
            'self_compassion': YesNo.Yes,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
        },
    },
    {
        InternalName: 'naming_thanking_mind',
        DisplayName: 'Naming&Thanking mind',
        Features: {
            three_five_mins: YesNo.Yes,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.Yes,
            zoom_out: YesNo.Yes,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
        },
    },
    {
        InternalName: '3_good_things',
        DisplayName: '3 Good Things',
        Features: {
            three_five_mins: YesNo.Yes,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.No,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.Yes,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
        },
    },
    {
        InternalName: 'labeling',
        DisplayName: 'Labeling',
        Features: {
            three_five_mins: YesNo.Yes,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.Yes,
            zoom_out: YesNo.Yes,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
        },
    },
    {
        InternalName: 'article_self_compassion',
        DisplayName: 'Article self compassion',
        Features: {
            three_five_mins: YesNo.Yes,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.No,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.No,
            self_compassion: YesNo.Yes,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.Yes,
        },
    },
    {
        InternalName: 'leaves_on_stream',
        DisplayName: 'Leaves on a stream',
        Features: {
            three_five_mins: YesNo.No,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.Yes,
            defuse: YesNo.Yes,
            zoom_out: YesNo.Yes,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
        },
    },
    {
        InternalName: 'bad_news_radio',
        DisplayName: 'Bad News Radio',
        Features: {
            three_five_mins: YesNo.Yes,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.Yes,
            zoom_out: YesNo.Yes,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
        },
    },
    {
        InternalName: 'milk_milk_milk',
        DisplayName: 'Milk Milk Milk',
        Features: {
            three_five_mins: YesNo.Yes,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.Yes,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
        },
    },
    {
        InternalName: 'article_breathing_relaxation',
        DisplayName: 'Article Breathing relaxation',
        Features: {
            three_five_mins: YesNo.Yes,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.No,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.Yes,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.Yes,
            feeling_anxious: YesNo.Yes,
            grounding: YesNo.No,
            feeling_blue: YesNo.Yes,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.Yes,
            article: YesNo.Yes,
        },
    },
    {
        InternalName: 'five_senses',
        DisplayName: 'Five Senses',
        Features: {
            three_five_mins: YesNo.No,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.Yes,
            defuse: YesNo.No,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.Yes,
            feeling_angry: YesNo.Yes,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.Yes,
            feeling_blue: YesNo.Yes,
            focus: YesNo.Yes,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
        },
    },
    {
        InternalName: 'tracking_thought_in_time',
        DisplayName: 'Tracking thoughts in time',
        Features: {
            three_five_mins: YesNo.Yes,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.No,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.Yes,
            feeling_blue: YesNo.No,
            focus: YesNo.Yes,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
        },
    },
    {
        InternalName: 'alternate_nostril_breathing',
        DisplayName: 'Alternate nostril breathing',
        Features: {
            three_five_mins: YesNo.No,
            five_seven_mins: YesNo.Yes,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.No,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.Yes,
            feeling_angry: YesNo.Yes,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.Yes,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.Yes,
            article: YesNo.No,
        },
    },
    {
        InternalName: 'boxed_breathing',
        DisplayName: 'Boxed Breathing',
        Features: {
            three_five_mins: YesNo.Yes,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.No,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.Yes,
            feeling_angry: YesNo.Yes,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.Yes,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.Yes,
            article: YesNo.No,
        },
    },
    {
        InternalName: 'diaphragmatic_breathing',
        DisplayName: 'Diaphragmatic Breathing',
        Features: {
            three_five_mins: YesNo.No,
            five_seven_mins: YesNo.Yes,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.No,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.Yes,
            feeling_angry: YesNo.Yes,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.Yes,
            article: YesNo.No,
        },
    },
    {
        InternalName: 'talking_to_friend',
        DisplayName: 'Talking to a friend',
        Features: {
            three_five_mins: YesNo.No,
            five_seven_mins: YesNo.Yes,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.No,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.No,
            self_compassion: YesNo.Yes,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
        },
    },
    {
        InternalName: 'article_positive_psychology',
        DisplayName: 'Article Positive Psychology',
        Features: {
            three_five_mins: YesNo.No,
            five_seven_mins: YesNo.Yes,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.No,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.Yes,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.Yes,
            feeling_anxious: YesNo.No,
            grounding: YesNo.Yes,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.Yes,
        },
    },
    {
        InternalName: 'savouring',
        DisplayName: 'Savouring',
        Features: {
            three_five_mins: YesNo.No,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.Yes,
            defuse: YesNo.No,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.Yes,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
        },
    },
    {
        InternalName: 'positive_self_talk',
        DisplayName: 'Positive Self Talk',
        Features: {
            three_five_mins: YesNo.No,
            five_seven_mins: YesNo.No,
            seven_ten_mins: YesNo.Yes,
            defuse: YesNo.No,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.Yes,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.No,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.No,
            article: YesNo.No,
        },
    },
    {
        InternalName: 'follow_your_breath',
        DisplayName: 'Follow Your Breath',
        Features: {
            three_five_mins: YesNo.No,
            five_seven_mins: YesNo.Yes,
            seven_ten_mins: YesNo.No,
            defuse: YesNo.No,
            zoom_out: YesNo.No,
            feeling_stressed: YesNo.No,
            feeling_angry: YesNo.No,
            mood_boost: YesNo.No,
            self_compassion: YesNo.No,
            relax: YesNo.No,
            energize: YesNo.No,
            feeling_anxious: YesNo.No,
            grounding: YesNo.Yes,
            feeling_blue: YesNo.No,
            focus: YesNo.No,
            shift_perspective: YesNo.No,
            introspect: YesNo.No,
            breathing: YesNo.Yes,
            article: YesNo.No,
        },
    },
    
]

// exerciseNames is a list of all the exercise DisplayNames:
export const exerciseNames = Exercises.map((exercise) => exercise.InternalName);